version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: newsdb
      POSTGRES_USER: newsuser
      POSTGRES_PASSWORD: newpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
     - "6379:6379"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A djangoProject worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  flower:
    build: .
    command: celery -A djangoProject flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
