# Generated by Django 3.2.25 on 2024-08-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='source',
            field=models.CharField(max_length=200),
        ),
    ]
